apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-deployment
  namespace: gitlab-agent-local
  labels:
    app: spring
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
      - name: spring
        image: registry.socs.uoguelph.ca/amerch04/springtemplate/spring:v0.0.1
        imagePullPolicy: Always
        env:
          - name: DB_ADDRESS
            value: jdbc:mysql://mysql-service:3306
          - name: DB_DATABASE
            value: template_db
          - name: DB_USER
            value: root
          - name: DB_PASSWORD
            value: pwd
      imagePullSecrets:
      - name : regcred
